import 'package:flutter/material.dart';

class Promos extends StatelessWidget {
  const Promos({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        title: Text("Promos"),
        leading: Icon(Icons.chevron_left),
      ),
      body: Container(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SingleChildScrollView(
            child: Column(
              children: [
                Divider(),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(
                    leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Welcome to Kangaroo Cars! Enjoy 20% OFF your first ride—use code KANGAROO20 at checkout."),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Welcome to Kangaroo Cars! Enjoy 20% OFF your first ride—use code KANGAROO20 at checkout."),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("New here? Hop in and save! 15% off on your first trip with promo NEWKANG."),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Love Kangaroo? Refer a friend and you’ll both get ₹200 ride credit!"),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Share your code ABC123—every successful friend sign-up earns you free rides."),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Flash Sale! Get 25% off between 5–8 PM today. Just open the app and tap “Flash Promo!"),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(
                    leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Welcome to Kangaroo Cars! Enjoy 20% OFF your first ride—use code KANGAROO20 at checkout."),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Welcome to Kangaroo Cars! Enjoy 20% OFF your first ride—use code KANGAROO20 at checkout."),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("New here? Hop in and save! 15% off on your first trip with promo NEWKANG."),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Love Kangaroo? Refer a friend and you’ll both get ₹200 ride credit!"),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Share your code ABC123—every successful friend sign-up earns you free rides."),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
                 Card(
                  color: Colors.amber,
                  // color: Colors.white,
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(leading:  const Icon(Icons.discount),
                    contentPadding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    title: Text(""),
                    subtitle: Text("Flash Sale! Get 25% off between 5–8 PM today. Just open the app and tap “Flash Promo!"),
                    trailing: const Icon(Icons.chevron_right),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}